### PR TITLE
website_sale_customer_type: Make compatible with website_sale_close

### PR DESCRIPTION
**Pull request by carmenbianca**
website_sale_customer_type wraps WebsiteSale.main from
website_sale_close. I do not know if the order is defined somewhere.

In any case, website_sale_customer_type now detects when it receives an
(incomplete) request from website_sale_close, and passes it along.

A better fix might be to return a compliant context from
website_sale_close?

Task: https://gestion.coopiteasy.be/web#id=7809&view_type=form&model=project.task

### CODE REVIEW

**Review by remytms — CHANGES_REQUESTED** [review]
Not sure if this code should stay in the `website_sale_customer_type`. It's OK, because the code will no bug if `website_sale_close` is not installed. Another way to fix it *may be* to create a new module that depends on `website_sale_close` and `website_sale_customer_type` and with a controller that overwrite the methods and call to `super` in the right order. But I'm not sure that this will work.

In any cases, the `def product()` method should be edited like the `def shop()` one. :)

**Comment by carmenbianca** [comment]
I think it'd be preferable to alter `website_sale_close` such that it doesn't break downstream consumers, but I'm not sure that's actually possible. Downstream would just render a different template.

I'm not sure how customary it is to create a module to make two incompatible modules compatible. I'm also not sure how to re-jig the inheritance tree from that third module. We'd need to make sure that the third module loads _last_ (or the re-jigging gets delayed), but if we could control the module load order, we could solve this problem anyway. Ideas?

Given that these two modules are in the same repository, it's _probably_ fine to just put the compatibility check in `website_sale_customer_type`.

**Comment by robinkeunen** [comment]
I did not try to understand the issue, I'm just reacting to 

> I'm not sure how customary it is to create a module to make two incompatible modules compatible.

Did you checkout the [auto_install](https://www.odoo.com/documentation/12.0/developer/reference/module.html#) parameter of the `__manifest__`?

**Comment by huguesdk** [comment]
i un-merged the branch. pr #14 now tracks these changes.

**Pull request merged**
